-- Work Management v1.21.6 — collaborative item workspace
begin;

create table if not exists public.work_board_item_updates (
  id bigint generated by default as identity primary key,
  board_id uuid not null references public.work_boards(id) on delete cascade,
  item_id uuid not null references public.work_board_items(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 5000),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists work_board_item_updates_item_idx on public.work_board_item_updates(item_id,created_at desc,id desc);

create table if not exists public.work_board_item_files (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references public.work_boards(id) on delete cascade,
  item_id uuid not null references public.work_board_items(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null check (char_length(file_name) between 1 and 240),
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null check (size_bytes between 0 and 20971520),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
create index if not exists work_board_item_files_item_idx on public.work_board_item_files(item_id,created_at desc);

alter table public.work_board_item_updates enable row level security;
alter table public.work_board_item_files enable row level security;
revoke all on public.work_board_item_updates, public.work_board_item_files from anon, authenticated;

create or replace function public.wm_get_board_item_workspace(p_item_id uuid) returns jsonb
language plpgsql stable security definer set search_path=public as $$
declare bid uuid; result jsonb;
begin
  select board_id into bid from public.work_board_items where id=p_item_id;
  if bid is null or not public.work_board_access(bid,'view') then raise exception 'Board access denied' using errcode='42501'; end if;
  select jsonb_build_object(
    'updates',coalesce((select jsonb_agg(jsonb_build_object(
      'id',u.id,'body',u.body,'created_by',u.created_by,'created_at',u.created_at,'updated_at',u.updated_at,
      'author_name',coalesce(p.display_name,p.email),'author_email',p.email,'can_delete',(u.created_by=auth.uid() or public.work_board_access(bid,'manage'))
    ) order by u.created_at desc,u.id desc) from public.work_board_item_updates u join public.profiles p on p.id=u.created_by where u.item_id=p_item_id),'[]'::jsonb),
    'files',coalesce((select jsonb_agg(jsonb_build_object(
      'id',f.id,'file_name',f.file_name,'mime_type',f.mime_type,'size_bytes',f.size_bytes,'storage_path',f.storage_path,
      'created_by',f.created_by,'created_at',f.created_at,'author_name',coalesce(p.display_name,p.email),'can_delete',(f.created_by=auth.uid() or public.work_board_access(bid,'manage'))
    ) order by f.created_at desc) from public.work_board_item_files f join public.profiles p on p.id=f.created_by where f.item_id=p_item_id),'[]'::jsonb),
    'activity',coalesce((select jsonb_agg(jsonb_build_object(
      'id',e.id,'event_type',e.event_type,'message',e.message,'payload',e.payload,'created_at',e.created_at,
      'actor_name',coalesce(p.display_name,p.email),'actor_email',p.email
    ) order by e.id desc) from public.work_board_events e join public.profiles p on p.id=e.actor_id where e.board_id=bid and e.entity_type='item' and e.entity_id=p_item_id::text),'[]'::jsonb)
  ) into result;
  return result;
end $$;

create or replace function public.wm_add_board_item_update(p_item_id uuid,p_body text) returns bigint
language plpgsql security definer set search_path=public as $$
declare bid uuid; uid bigint;
begin
  select board_id into bid from public.work_board_items where id=p_item_id;
  if bid is null or not public.work_board_access(bid,'view') then raise exception 'Board access denied' using errcode='42501'; end if;
  if char_length(btrim(coalesce(p_body,''))) not between 1 and 5000 then raise exception 'Update must contain 1-5000 characters'; end if;
  insert into public.work_board_item_updates(board_id,item_id,body,created_by) values(bid,p_item_id,btrim(p_body),auth.uid()) returning id into uid;
  update public.work_boards set updated_at=now(),updated_by=auth.uid() where id=bid;
  perform public.work_board_log(bid,'item.update_added','Update posted','item',p_item_id::text,jsonb_build_object('update_id',uid));
  return uid;
end $$;

create or replace function public.wm_delete_board_item_update(p_update_id bigint) returns void
language plpgsql security definer set search_path=public as $$
declare row_now public.work_board_item_updates%rowtype;
begin
  select * into row_now from public.work_board_item_updates where id=p_update_id;
  if row_now.id is null or not public.work_board_access(row_now.board_id,'view') then raise exception 'Update not found'; end if;
  if row_now.created_by<>auth.uid() and not public.work_board_access(row_now.board_id,'manage') then raise exception 'Only the update author or board owner can delete this update' using errcode='42501'; end if;
  delete from public.work_board_item_updates where id=p_update_id;
  perform public.work_board_log(row_now.board_id,'item.update_deleted','Update deleted','item',row_now.item_id::text,jsonb_build_object('update_id',p_update_id));
end $$;

create or replace function public.wm_register_board_item_file(p_item_id uuid,p_storage_path text,p_file_name text,p_mime_type text,p_size_bytes bigint) returns uuid
language plpgsql security definer set search_path=public as $$
declare bid uuid; fid uuid;
begin
  select board_id into bid from public.work_board_items where id=p_item_id;
  if bid is null or not public.work_board_access(bid,'view') then raise exception 'Board access denied' using errcode='42501'; end if;
  if char_length(btrim(coalesce(p_file_name,''))) not between 1 and 240 then raise exception 'Invalid file name'; end if;
  if coalesce(p_size_bytes,-1) not between 0 and 20971520 then raise exception 'Files must be 20 MB or smaller'; end if;
  if p_storage_path not like bid::text||'/'||p_item_id::text||'/%' then raise exception 'Invalid file path'; end if;
  insert into public.work_board_item_files(board_id,item_id,storage_path,file_name,mime_type,size_bytes,created_by)
  values(bid,p_item_id,p_storage_path,btrim(p_file_name),left(coalesce(nullif(p_mime_type,''),'application/octet-stream'),160),p_size_bytes,auth.uid()) returning id into fid;
  update public.work_boards set updated_at=now(),updated_by=auth.uid() where id=bid;
  perform public.work_board_log(bid,'item.file_added','File attached','item',p_item_id::text,jsonb_build_object('file_id',fid,'file_name',btrim(p_file_name)));
  return fid;
end $$;

create or replace function public.wm_delete_board_item_file(p_file_id uuid) returns text
language plpgsql security definer set search_path=public as $$
declare row_now public.work_board_item_files%rowtype;
begin
  select * into row_now from public.work_board_item_files where id=p_file_id;
  if row_now.id is null or not public.work_board_access(row_now.board_id,'view') then raise exception 'File not found'; end if;
  if row_now.created_by<>auth.uid() and not public.work_board_access(row_now.board_id,'manage') then raise exception 'Only the uploader or board owner can remove this file' using errcode='42501'; end if;
  delete from public.work_board_item_files where id=p_file_id;
  perform public.work_board_log(row_now.board_id,'item.file_deleted','File removed','item',row_now.item_id::text,jsonb_build_object('file_id',p_file_id,'file_name',row_now.file_name));
  return row_now.storage_path;
end $$;

revoke all on function public.wm_get_board_item_workspace(uuid) from public;
revoke all on function public.wm_add_board_item_update(uuid,text) from public;
revoke all on function public.wm_delete_board_item_update(bigint) from public;
revoke all on function public.wm_register_board_item_file(uuid,text,text,text,bigint) from public;
revoke all on function public.wm_delete_board_item_file(uuid) from public;
grant execute on function public.wm_get_board_item_workspace(uuid) to authenticated;
grant execute on function public.wm_add_board_item_update(uuid,text) to authenticated;
grant execute on function public.wm_delete_board_item_update(bigint) to authenticated;
grant execute on function public.wm_register_board_item_file(uuid,text,text,text,bigint) to authenticated;
grant execute on function public.wm_delete_board_item_file(uuid) to authenticated;

-- Private Supabase Storage bucket used by item attachments.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('work-board-files','work-board-files',false,20971520,null)
on conflict(id) do update set public=false,file_size_limit=20971520;

drop policy if exists "wm board files read" on storage.objects;
drop policy if exists "wm board files insert" on storage.objects;
drop policy if exists "wm board files delete" on storage.objects;
create policy "wm board files read" on storage.objects for select to authenticated using (
  bucket_id='work-board-files' and public.work_board_access(((storage.foldername(name))[1])::uuid,'view')
);
create policy "wm board files insert" on storage.objects for insert to authenticated with check (
  bucket_id='work-board-files' and owner_id=auth.uid()::text and public.work_board_access(((storage.foldername(name))[1])::uuid,'view')
);
create policy "wm board files delete" on storage.objects for delete to authenticated using (
  bucket_id='work-board-files' and (owner_id=auth.uid()::text or public.work_board_access(((storage.foldername(name))[1])::uuid,'manage'))
);

create or replace function public.wm_board_backend_capabilities() returns jsonb
language sql stable security definer set search_path=public as $$
  select jsonb_build_object('schema_version','1.21.6','flexible_board_creation',true,'configured_create',true,'empty_boards',true,'removable_custom_columns',true,'item_workspace',true,'item_updates',true,'item_files',true,'item_activity',true);
$$;
revoke all on function public.wm_board_backend_capabilities() from public;
grant execute on function public.wm_board_backend_capabilities() to authenticated;
notify pgrst, 'reload schema';
commit;
